sudo: false
dist: trusty
language: cpp

addons:
  apt:
    packages:

matrix:
  include:

    # XCode 9.3
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - CMAKE_OPTNS="-D CMAKE_BUILD_TYPE=Debug"

    # GCC 5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-dev
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - CMAKE_OPTNS="-D Template_ENABLE_COVERAGE:BOOL=TRUE
                       -D CMAKE_BUILD_TYPE=Debug"

    # GCC 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CMAKE_OPTNS="-D Template_ENABLE_COVERAGE:BOOL=TRUE
                       -D CMAKE_BUILD_TYPE=Debug"

    # GCC 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-dev
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CMAKE_OPTNS="-D Template_ENABLE_COVERAGE:BOOL=TRUE
                       -D CMAKE_BUILD_TYPE=Debug"

    # Clang 4.0
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        - CMAKE_OPTNS="-D Template_USE_CLANG_TIDY:BOOL=TRUE 
                       -D Template_MEMCHECK:BOOL=TRUE 
                       -D CMAKE_BUILD_TYPE=Debug"

    # Clang 5.0
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - CMAKE_OPTNS="-D Template_USE_CLANG_TIDY:BOOL=TRUE
                       -D Template_MEMCHECK:BOOL=TRUE
                       -D CMAKE_BUILD_TYPE=Debug"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake $CMAKE_OPTNS ..
  - make -j 4
  - ./test/simple_tests

# after_success:
#   # Creating report
#   - cd ${TRAVIS_BUILD_DIR}
#   # capture coverage info
#   - lcov --directory . --capture --output-file coverage.info 
#   # filter out system and catch headers
#   - lcov --remove coverage.info '/usr/*' 'tests/catch.hpp' --output-file coverage.info 
#   # debug info
#   - lcov --list coverage.info 
#   # Uploading report to CodeCov
#   - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
