image:
  - Visual Studio 2017

configuration:
  - Debug

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake ..

    cmake --build . --config %CONFIGURATION%
 
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS

