image:
  - Visual Studio 2017

clone_folder: c:\projects\source

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_64_0

test_script:
- cmd: >-
    ./build-and-run
