image:
  - Visual Studio 2017

clone_folder: c:\projects\source

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_64_0

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\projects\source ..

    cmake --build .

test_script:
- cmd: ./test/simple_tests

