image:
  - Visual Studio 2017

configuration:
  - Debug

clone_folder: d:\projects\source

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake d:\projects\source ..

    cmake --build . --config %CONFIGURATION%
 
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS

