image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

clone_folder: c:\projects\source

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_64_0

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\projects\source ..

    cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS

