image:
  - Visual Studio 2017

configuration:
  - Debug

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake ..

    cmake --build . --config %CONFIGURATION%
    
# https://stackoverflow.com/questions/31457306/visual-studio-msb3073-error-exited-with-code-1
#test_script:
#  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS

